---
title: "Cheesy"
date: 2018-11-07
---
author: Colby
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  github course thing

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
